name: Game Animations
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  game-animations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate Bouncing Ball SVG
        run: |
          echo '<svg width="120" height="60" xmlns="http://www.w3.org/2000/svg">
            <rect width="120" height="60" fill="#222" />
            <circle cx="20" cy="30" r="10" fill="#F7C948">
              <animate attributeName="cx" values="20;100;20" dur="2s" repeatCount="indefinite" />
              <animate attributeName="cy" values="30;50;30" dur="1s" repeatCount="indefinite" />
            </circle>
          </svg>' > assets/bouncing-ball.svg
      - name: Generate Walking Character SVG
        run: |
          echo '<svg width="120" height="60" xmlns="http://www.w3.org/2000/svg">
            <rect width="120" height="60" fill="#222" />
            <rect x="10" y="40" width="20" height="10" fill="#2F81F7">
              <animate attributeName="x" values="10;90;10" dur="3s" repeatCount="indefinite" />
            </rect>
            <circle cx="20" cy="35" r="5" fill="#F7C948">
              <animate attributeName="cx" values="20;100;20" dur="3s" repeatCount="indefinite" />
            </circle>
          </svg>' > assets/walking-character.svg
      - name: Generate Pixel Art LED SVG
        run: |
          echo '<svg width="60" height="20" xmlns="http://www.w3.org/2000/svg">
            <rect width="60" height="20" fill="#222" />
            <rect x="10" y="5" width="10" height="10" fill="#F7C948">
              <animate attributeName="fill" values="#F7C948;#222;#F7C948" dur="1s" repeatCount="indefinite" />
            </rect>
            <rect x="30" y="5" width="10" height="10" fill="#2F81F7">
              <animate attributeName="fill" values="#2F81F7;#222;#2F81F7" dur="1s" begin="0.5s" repeatCount="indefinite" />
            </rect>
          </svg>' > assets/pixel-led.svg
      - name: Generate Game Progress Bar SVG
        run: |
          echo '<svg width="120" height="20" xmlns="http://www.w3.org/2000/svg">
            <rect width="120" height="20" fill="#222" />
            <rect x="5" y="5" width="110" height="10" fill="#555" rx="5" />
            <rect x="5" y="5" width="0" height="10" fill="#2F81F7" rx="5">
              <animate attributeName="width" values="0;110;0" dur="2s" repeatCount="indefinite" />
            </rect>
          </svg>' > assets/progress-bar.svg
      - name: Commit and push SVGs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add assets/*.svg
          git commit -m "Add game-like SVG animations via GitHub Actions" || echo "No changes to commit"
          git push
